<a href="https://colab.research.google.com/github/katiejoy97/katiejoy97/blob/main/00_pytorch_execises.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch


In [2]:
# Create a random tensor with shape (7,7).
torch.rand(7,7)

tensor([[0.0626, 0.4807, 0.3539, 0.6097, 0.4180, 0.0190, 0.4271],
        [0.4404, 0.5409, 0.4713, 0.8268, 0.8170, 0.0321, 0.1471],
        [0.4548, 0.9482, 0.7964, 0.2972, 0.7762, 0.0086, 0.4018],
        [0.7440, 0.0566, 0.4563, 0.3476, 0.9723, 0.7385, 0.8748],
        [0.0387, 0.1868, 0.4264, 0.8562, 0.6757, 0.3155, 0.2762],
        [0.8304, 0.6742, 0.4394, 0.1247, 0.7711, 0.6621, 0.3699],
        [0.9955, 0.1635, 0.3098, 0.1765, 0.9916, 0.8683, 0.7195]])

In [3]:
#Create random tensor
X = torch.rand(size=(7,7))
X, X.shape

(tensor([[0.2041, 0.9149, 0.1802, 0.3784, 0.6948, 0.8822, 0.0927],
         [0.0709, 0.0353, 0.7064, 0.8118, 0.8580, 0.5888, 0.0995],
         [0.7428, 0.1887, 0.0444, 0.9984, 0.1059, 0.6996, 0.6334],
         [0.8580, 0.1170, 0.7937, 0.0944, 0.6097, 0.2429, 0.1533],
         [0.3783, 0.2789, 0.8047, 0.9094, 0.9556, 0.7396, 0.3073],
         [0.6138, 0.5413, 0.6660, 0.0055, 0.3472, 0.5623, 0.2304],
         [0.7631, 0.7488, 0.5056, 0.0044, 0.0510, 0.4188, 0.0150]]),
 torch.Size([7, 7]))

In [4]:
#Create another random tensor
Y = torch.rand(size=(1,7))
#Z = torch.matmul(X, Y) # will error because of shape issues
Z = torch.matmul(X, Y.T) # no error because of transpose
Z, Z.shape

(tensor([[1.6848],
         [1.0027],
         [1.2895],
         [0.9012],
         [1.5889],
         [1.3545],
         [1.1337]]),
 torch.Size([7, 1]))

In [5]:
#Set manual seed
torch.manual_seed(0)

#Create two random tensors
X= torch.rand(size=(7,7))
Y= torch.rand(size=(1,7))

#Matrix multiply tensors
Z= torch.matmul(X, Y.T)
Z, Z.shape

(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]),
 torch.Size([7, 1]))

In [6]:
#Set random seed on the GPU
torch.cuda.manual_seed(1234)

In [7]:
#Set rabdom seed
torch.manual_seed(1234)

#Check for access to GPU
device = "cuda" if torch.cuda.is_available() else "cpu"
print(f"Device: {device}")

#Create two random tensors on GPU
tensor_A = torch.rand(size=(2,3)).to(device)
tensor_B = torch.rand(size=(2,3)).to(device)
tensor_A, tensor_B

Device: cuda


(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))

In [8]:
#Perform matmul on tensor_A and tensor_B
#tensor_C = torch.matmul(tensor_A, tesnor_B) # won't work because of shape error
tensor_C=torch.matmul(tensor_A, tensor_B.T)
tensor_C, tensor_C.shape

(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'),
 torch.Size([2, 2]))

In [9]:
#Find max
max=torch.max(tensor_C)

#Find min
min = torch.min(tensor_C)
max,min

(tensor(0.5617, device='cuda:0'), tensor(0.3647, device='cuda:0'))

In [11]:
#Find arg max
arg_max = torch.argmax(tensor_C)

#Find arg min
arg_min = torch.argmin(tensor_C)
arg_max, arg_min

(tensor(3, device='cuda:0'), tensor(0, device='cuda:0'))

In [12]:
#set seed
torch.manual_seed(7)

#Create random tensor
tensor_D = torch.rand(size=(1,1,1,10))

#Remove single dimensions
tensor_E = tensor_D.squeeze()

#Print out tensors

print(tensor_D, tensor_D.shape)
print(tensor_E, tensor_E.shape)


tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
