<a href="https://colab.research.google.com/github/katiejoy97/katiejoy97/blob/main/pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import torch

In [4]:
torch.cuda.is_available()


True

In [5]:
#setup device agnostic code

In [6]:
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [8]:
#count number of devices
torch.cuda.device_count()


1

In [ ]:
## Putting Tensors and models on the GPU
The reaason we want our tensors/models on the GPU is because using a GPU results in faster computations



In [9]:
tensor = torch.tensor([1,2,3], device="cpu")

print (tensor,tensor.device)

tensor([1, 2, 3]) cpu


In [10]:
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

In [12]:
### Moving tensors back to the CPU
# if tensor is on GPU, cant transform it to numpy

tensor_on_gpu.numpy()

TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

In [13]:
#to fix the gpu tensor with Numpy issue, we can first set it to the CPu
tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu



array([1, 2, 3])

In [14]:
tensor_on_gpu


tensor([1, 2, 3], device='cuda:0')

In [15]:
!nvidia-smi


Tue Oct  8 15:22:59 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.104.05             Driver Version: 535.104.05   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Tesla T4                       Off | 00000000:00:04.0 Off |                    0 |
| N/A   65C    P0              30W /  70W |    105MiB / 15360MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--